// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where (if anywhere) an Anthropic key is available.
 */
export type AiKeyStatus = { 
/**
 * A key is stored in the OS keychain.
 */
stored: boolean, 
/**
 * The `ANTHROPIC_API_KEY` env var is set.
 */
env: boolean, };
