// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why an AI call is being made — tagged for per-purpose cost analytics.
 */
export type AiPurpose = "lyric_format" | "theme_generate" | "bible_search" | "service_plan";
