// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a "test connection" probe.
 */
export type AiTestResult = { ok: boolean, message: string, };
