// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One position in an arrangement's ordered sequence. The same `section_id`
 * may appear at multiple positions (verse → chorus → verse → chorus).
 */
export type ArrangementItem = { arrangement_id: string, position: bigint, section_id: string, };
