// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A translation the operator can install, with how much of it is present now.
 */
export type AvailableTranslation = { code: string, name: string, language: string, 
/**
 * Approximate download size in bytes (the pinned file length).
 */
approxBytes: number, 
/**
 * Verses of this code already in the library: 0 = not installed, a small
 * number = the bundled starter set, ~31k = the full corpus.
 */
installedVerses: number, };
