// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the slide's full-frame background is painted.
 */
export type BackgroundKind = "color" | "image" | "video" | "gradient";
