// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BibleReference = { id: string, book: string, chapter: bigint, verse_start: bigint, verse_end: bigint | null, translation: string, text: string, created_at: bigint, };
