// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which phase a running download is in, for the progress event.
 */
export type BibleDownloadPhase = "downloading" | "verifying" | "installing" | "done";
