// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A book in a translation, with its localized display name.
 */
export type BibleBook = { book: string, book_order: bigint, display: string, };
