// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BibleDownloadPhase } from "./BibleDownloadPhase";

/**
 * A progress tick emitted on [`PROGRESS_EVENT`] while a corpus downloads.
 */
export type BibleDownloadProgress = { 
/**
 * The translation code being installed.
 */
code: string, phase: BibleDownloadPhase, 
/**
 * Bytes downloaded so far (only meaningful in the `downloading` phase).
 */
downloaded: number, 
/**
 * Total bytes expected.
 */
total: number, };
