// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BibleVerse } from "./BibleVerse";

/**
 * A resolved passage: the verses plus a tidy display reference.
 */
export type BiblePassage = { reference: string, verses: Array<BibleVerse>, };
