// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single verse of a translation.
 */
export type BibleVerse = { id: string, translation_id: string, book: string, book_order: bigint, chapter: bigint, verse: bigint, text: string, created_at: bigint, };
