// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An installed translation (a bundled public-domain text, or a downloaded one).
 */
export type BibleTranslation = { id: string, code: string, name: string, language: string, public_domain: bigint, created_at: bigint, };
