// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of content the phone should render.
 */
export type BroadcastKind = "lyric" | "scripture" | "announcement" | "blackout";
