// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BroadcastKind } from "./BroadcastKind";

/**
 * The text-only payload a phone receives. Versioned; ordered by `seq`.
 */
export type BroadcastFrame = { v: number, kind: BroadcastKind, text: string, section_label: string | null, reference: string | null, seq: number, };
