// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A recording chapter marker: milliseconds from the start of the session, plus
 * a human title.
 */
export type ChapterMarker = { offset_ms: bigint, title: string, };
