// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Claude model the app can call, with pricing for cost estimates.
 */
export type ClaudeModel = { 
/**
 * API id, e.g. `claude-sonnet-4-6`.
 */
id: string, display: string, 
/**
 * USD per million input tokens.
 */
input_price_per_mtok: number, 
/**
 * USD per million output tokens.
 */
output_price_per_mtok: number, 
/**
 * Heavier/pricier model suited to deep tasks (theme gen, planning).
 */
heavy: boolean, };
