// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three states the UI has to tell apart.
 */
export type ConsentStatus = "never-asked" | "granted" | "denied";
