// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CounterName } from "./CounterName";

/**
 * One counter's accumulated total, for the read command.
 */
export type CounterTotal = { 
/**
 * Serialises AS the dotted wire string — see [`CounterName`]'s serde
 * renames — so a reader never has to map the enum to a name.
 */
name: CounterName, 
/**
 * Persisted total plus anything still buffered in memory.
 */
value: number, };
