// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every counter name that may ever appear on the wire.
 */
export type CounterName = "live.session.started" | "live.session.ended" | "live.session.recovered" | "live.cue.dispatched" | "output.opened" | "output.fallback.in_process" | "editor.service.created" | "editor.song.created" | "ai.format.run" | "ai.search.run" | "library.publish.run" | "library.import.run" | "bible.verse.projected" | "deck.presented" | "theme.created" | "companion.connected" | "template.applied" | "update.installed" | "report.manual.sent";
