// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CounterName } from "./CounterName";

/**
 * One counter's DELTA since the last report.
 */
export type CounterReport = { 
/**
 * Serialises AS the dotted wire string — see [`CounterName`]'s serde
 * renames.
 */
name: CounterName, value: number, };
