// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrashKind } from "./CrashKind";
import type { TelemetryOs } from "./TelemetryOs";

/**
 * One crash record, as it goes on the wire.
 *
 * The E3 ring already writes records in this shape — scrubbed, capped at
 * exactly the wire limits — so this is a projection that drops `schema` and
 * changes NO string. There is deliberately no second truncation pass that could
 * disagree with the one that wrote the file.
 */
export type CrashReport = { kind: CrashKind, at: number, appVersion: string, os: TelemetryOs, message: string, location: string | null, task: string | null, backtracePresent: boolean, };
