// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrashKind } from "./CrashKind";
import type { TelemetryOs } from "./TelemetryOs";

/**
 * One persisted crash record — already wire-shaped.
 *
 * The fields are exactly the programme's `crashes` shape. Everything free-form
 * has been through [`scrub`] and is capped, so the file on disk is what a
 * later release would send, byte for byte. There is no second truncation pass
 * that could disagree with the Worker's.
 */
export type CrashEntry = { 
/**
 * [`RECORD_SCHEMA`] at write time.
 */
schema: number, kind: CrashKind, 
/**
 * Unix ms (UTC) the record was written.
 */
at: number, 
/**
 * The app version that crashed — often NOT the version reading the ring,
 * which is exactly why it travels with the record.
 */
appVersion: string, os: TelemetryOs, 
/**
 * Scrubbed, capped at [`MESSAGE_MAX_CHARS`] (+1 for the ellipsis).
 */
message: string, 
/**
 * `file:line:col`, same treatment. `None` when the source carried none.
 */
location: string | null, 
/**
 * The task / component name, for the task kinds.
 */
task: string | null, 
/**
 * Whether a backtrace exists ON THIS MACHINE. The backtrace itself is not
 * stored in v1: it names every source file it walked through, which on a
 * machine built from source is a directory listing of someone's disk. The
 * boolean answers the only question an aggregate can ask of it ("was one
 * available?") at zero privacy cost.
 */
backtracePresent: boolean, };
