// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of crash-adjacent event a record describes. A CLOSED set: this is
 * the field an aggregate is grouped by, and a free-form string here would be
 * the one place a caller could widen the wire.
 *
 * An output-child death is deliberately absent — that is a quality signal, not
 * a crash: the projector kept showing its frame throughout.
 */
export type CrashKind = "panic" | "task_panic" | "webview_error" | "unhandled_rejection" | "other";
