// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CueSource } from "./CueSource";
import type { SlideContent } from "./SlideContent";

/**
 * A single executable step in the live timeline. Discriminated by `kind`.
 *
 * JSON-friendly because the engine persists the compiled list and the
 * renderer reads it for the operator UI.
 */
export type Cue = { "kind": "show_slide", cue_id: string, slide_content: SlideContent, 
/**
 * Optional theme/template override resolved at compile time.
 */
theme_id: string | null, template_id: string | null, 
/**
 * Back-reference for the operator UI.
 */
source: CueSource, } | { "kind": "black_out", cue_id: string, } | { "kind": "show_logo", cue_id: string, } | { "kind": "pause", cue_id: string, label: string, };
