// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CueSource } from "./CueSource";
import type { SlideContent } from "./SlideContent";

/**
 * A single executable step in the live timeline. Discriminated by `kind`.
 *
 * JSON-friendly because the engine persists the compiled list and the
 * renderer reads it for the operator UI.
 */
export type Cue = { "kind": "show_slide", cue_id: string, slide_content: SlideContent, 
/**
 * The CONCRETE theme/template resolved through the cascade
 * (slide → song → library default → built-in) at compile time —
 * `Some` on every compiled cue; `None` only in pre-cascade persisted
 * sessions. The *resolved look* itself rides on
 * `slide_content.appearance` so the output needs no lookup.
 */
theme_id: string | null, template_id: string | null, 
/**
 * Back-reference for the operator UI.
 */
source: CueSource, } | { "kind": "black_out", cue_id: string, } | { "kind": "show_logo", cue_id: string, } | { "kind": "pause", cue_id: string, label: string, };
