// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cue } from "./Cue";

/**
 * A compiled live session. Persisted to disk on "Go Live"; survives
 * renderer crashes.
 */
export type CueList = { service_id: string, compiled_at: bigint, cues: Array<Cue>, };
