// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single slot specification inside a service template.
 */
export type CueSpec = { 
/**
 * The kind of cue this slot expects.
 */
kind: string, 
/**
 * Human-readable label shown in the queue.
 */
label: string, 
/**
 * Optional planning notes for this slot.
 */
notes: string | null, };
