// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceItemCues } from "./ServiceItemCues";

/**
 * A planning-time breakdown of what each service item contributes to the
 * queue. Produced by [`CueCompiler::summarize`] from the *same* per-item
 * compilation the live engine runs, so the numbers shown while planning match
 * the cues that actually play. Drives the "what goes into the queue for which
 * song" view in the service/queue editor.
 */
export type CueSummary = { service_id: string, total_cues: number, items: Array<ServiceItemCues>, };
