// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where in the source data this cue came from. Used by the operator UI
 * to highlight "you are here" in the service plan.
 */
export type CueSource = { service_item_id: string, 
/**
 * 0-based index of this cue within the service-item it came from.
 */
item_cue_index: number, 
/**
 * Display label for the operator UI: "Amazing Grace — Verse 2".
 */
display_label: string, };
