// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What was created, for the onboarding confirmation.
 */
export type DemoSummary = { songs: number, service_id: string, deck_id: string, };
