// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayRole } from "./DisplayRole";

/**
 * Binds a monitor to a role.
 */
export type DisplayAssignment = { monitor_index: number, role: DisplayRole, };
