// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a given physical screen is used for.
 */
export type DisplayRole = "main_output" | "stage_display" | "confidence_monitor" | "off";
