// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many displays this machine has. Nobody has two hundred screens, and the
 * difference between one and two is the difference between "the operator is
 * looking at the projector output" and a real multi-display rig.
 */
export type DisplayBucket = "none" | "one" | "two" | "three" | "four_plus";
