// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of importing a whole EasyWorship library folder.
 */
export type EasyWorshipImportResult = { 
/**
 * Songs created in the target library.
 */
imported: number, 
/**
 * Songs left untouched — a same-title song already existed, or the entry
 * had neither a title nor any lyrics to import.
 */
skipped: number, 
/**
 * Total songs read from the EasyWorship database.
 */
total: number, 
/**
 * Per-song failures ("«title»: reason"); the import continues past them.
 */
errors: Array<string>, };
