// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One labelled lyric block in a formatted song.
 */
export type FormattedSection = { 
/**
 * Canonical snake_case label, e.g. `verse_1`, `chorus`, `pre_chorus`.
 */
label: string, 
/**
 * Lyrics, newline-separated.
 */
lyrics: string, };
