// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormattedSection } from "./FormattedSection";

/**
 * The structured result of formatting raw lyrics.
 */
export type FormattedSong = { title_suggestion: string | null, 
/**
 * ISO-639-1 language guess, e.g. `no`, `en`.
 */
language: string, sections: Array<FormattedSection>, 
/**
 * Ordered section labels (repeats allowed): verse_1 → chorus → verse_2 → …
 */
arrangement: Array<string>, 
/**
 * Notes for the user (dropped arrangement refs, low confidence, …).
 */
warnings: Array<string>, };
