// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Horizontal text alignment within a block.
 */
export type HAlign = "left" | "center" | "right";
