// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportFormat } from "./ImportFormat";

/**
 * Outcome of importing one song file.
 */
export type ImportResult = { song_id: string, title: string, format: ImportFormat, section_count: number, warnings: Array<string>, };
