// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The file formats the importer recognises.
 */
export type ImportFormat = "plain_text" | "chord_pro" | "open_song" | "open_lyrics";
