/**
 * Type bindings auto-generated by `ts-rs` from Rust models in
 * `src-tauri/src/db/models.rs`. Do not edit individual files by hand —
 * they are regenerated by `cargo test export_bindings`.
 *
 * This barrel re-exports everything for ergonomic imports:
 *   import type { Song, Library } from "@/lib/bindings";
 */

export type { BibleReference }    from "./BibleReference";
export type { Cue }               from "./Cue";
export type { CueList }           from "./CueList";
export type { CueSource }         from "./CueSource";
export type { CustomDeck }        from "./CustomDeck";
export type { Library }           from "./Library";
export type { LibraryInput }      from "./LibraryInput";
export type { MediaAsset }        from "./MediaAsset";
export type { Person }            from "./Person";
export type { SearchResult }      from "./SearchResult";
export type { Service }           from "./Service";
export type { ServiceItem }       from "./ServiceItem";
export type { Slide }             from "./Slide";
export type { SlideContent }      from "./SlideContent";
export type { Song }              from "./Song";
export type { SongArrangement }   from "./SongArrangement";
export type { SongInput }         from "./SongInput";
export type { SongSection }       from "./SongSection";
export type { Tag }               from "./Tag";
export type { Template }          from "./Template";
export type { Theme }             from "./Theme";

/** Error shape returned by every Tauri command (see error.rs). */
export interface AppError {
  code:
    | "database"
    | "migration"
    | "not_found"
    | "conflict"
    | "validation"
    | "io"
    | "json"
    | "internal";
  message: string;
}
