/**
 * Type bindings auto-generated by `ts-rs` from Rust models in
 * `src-tauri/src/db/models.rs`. Do not edit individual files by hand —
 * they are regenerated by `cargo test export_bindings`.
 *
 * This barrel re-exports everything for ergonomic imports:
 *   import type { Song, Library } from "@/lib/bindings";
 */

export type { AiKeyStatus }       from "./AiKeyStatus";
export type { AiPurpose }         from "./AiPurpose";
export type { AiTestResult }      from "./AiTestResult";
export type { ArrangementItem }   from "./ArrangementItem";
export type { AvailableTranslation } from "./AvailableTranslation";
export type { BackgroundKind }    from "./BackgroundKind";
export type { BibleBook }         from "./BibleBook";
export type { BibleDownloadPhase } from "./BibleDownloadPhase";
export type { BibleDownloadProgress } from "./BibleDownloadProgress";
export type { BiblePassage }      from "./BiblePassage";
export type { BibleReference }    from "./BibleReference";
export type { BibleTranslation }  from "./BibleTranslation";
export type { BibleVerse }        from "./BibleVerse";
export type { ClaudeModel }       from "./ClaudeModel";
export type { Cue }               from "./Cue";
export type { CueList }           from "./CueList";
export type { CueSummary }        from "./CueSummary";
export type { CueSpec }           from "./CueSpec";
export type { ServiceItemCues }   from "./ServiceItemCues";
export type { SectionCueCount }   from "./SectionCueCount";
export type { ChapterMarker }     from "./ChapterMarker";
export type { CueSource }         from "./CueSource";
export type { CustomDeck }        from "./CustomDeck";
export type { DemoSummary }       from "./DemoSummary";
export type { DisplayAssignment } from "./DisplayAssignment";
export type { DisplayRole }       from "./DisplayRole";
export type { EasyWorshipImportResult } from "./EasyWorshipImportResult";
export type { FormattedSection }  from "./FormattedSection";
export type { FormattedSong }     from "./FormattedSong";
export type { HAlign }            from "./HAlign";
export type { ImportFormat }      from "./ImportFormat";
export type { ImportResult }      from "./ImportResult";
export type { Library }           from "./Library";
export type { LibraryInput }      from "./LibraryInput";
export type { LiveAction }        from "./LiveAction";
export type { LiveFrame }         from "./LiveFrame";
export type { LiveSessionView }   from "./LiveSessionView";
export type { LocaleInfo }        from "./LocaleInfo";
export type { MonitorInfo }       from "./MonitorInfo";
export type { OutputConfig }      from "./OutputConfig";
export type { OutputAppearance }  from "./OutputAppearance";
export type { OutputDisplayConfig } from "./OutputDisplayConfig";
export type { OutputResolution }  from "./OutputResolution";
export type { OutputTransition }  from "./OutputTransition";
export type { OutputState }       from "./OutputState";
export type { MediaAsset }        from "./MediaAsset";
export type { MediaStatus }       from "./MediaStatus";
export type { Person }            from "./Person";
export type { PlanItem }          from "./PlanItem";
export type { PlanImportResult }  from "./PlanImportResult";
export type { SearchResult }      from "./SearchResult";
export type { ServicePlan }       from "./ServicePlan";
export type { Service }           from "./Service";
export type { ServiceItem }       from "./ServiceItem";
export type { ServiceItemSong }   from "./ServiceItemSong";
export type { ServiceTemplate }   from "./ServiceTemplate";
export type { ServiceTemplateInput } from "./ServiceTemplateInput";
export type { Slide }             from "./Slide";
export type { SlideBackground }   from "./SlideBackground";
export type { SlideBlock }        from "./SlideBlock";
export type { SlideContent }      from "./SlideContent";
export type { SlideDoc }          from "./SlideDoc";
export type { SlideContentPayload } from "./SlideContentPayload";
export type { SlideRect }         from "./SlideRect";
export type { Song }              from "./Song";
export type { SongArrangement }   from "./SongArrangement";
export type { SongInput }         from "./SongInput";
export type { SongSection }       from "./SongSection";
export type { SongUsageRow }      from "./SongUsageRow";
export type { SlotRole }          from "./SlotRole";
export type { StageDisplayConfig } from "./StageDisplayConfig";
export type { SyncStatus }        from "./SyncStatus";
export type { Tag }               from "./Tag";
export type { Template }          from "./Template";
export type { TemplateRole }      from "./TemplateRole";
export type { TemplateLayout }    from "./TemplateLayout";
export type { TemplateSlot }      from "./TemplateSlot";
export type { TextStyle }         from "./TextStyle";
export type { Theme }             from "./Theme";
export type { ThemeTokens }       from "./ThemeTokens";
export type { TonoEntry }         from "./TonoEntry";
export type { TranslationResult } from "./TranslationResult";
export type { UniversalHit }      from "./UniversalHit";
export type { UpdateChannel }     from "./UpdateChannel";
export type { UpdateInfo }        from "./UpdateInfo";
export type { VAlign }            from "./VAlign";

// ── Local observation (E3) ───────────────────────────────────────────────────
// Nothing in this group is sent anywhere; see src-tauri/src/telemetry.
export type { CounterName }       from "./CounterName";
export type { CounterTotal }      from "./CounterTotal";
export type { CrashEntry }        from "./CrashEntry";
export type { CrashKind }         from "./CrashKind";
export type { QualityReason }     from "./QualityReason";
export type { QualityRow }        from "./QualityRow";
export type { QualityVerdict }    from "./QualityVerdict";
export type { TelemetryFlush }    from "./TelemetryFlush";
export type { TelemetryOs }       from "./TelemetryOs";

// ── The telemetry client (E5) ────────────────────────────────────────────────
// The machinery that COULD send, and does not: there is no UI to answer the
// consent question until E6, so the record stays absent and every path below it
// is inert. See src-tauri/src/telemetry/{consent,client,payload,outbox}.rs.
export type { ConsentStatus }     from "./ConsentStatus";
export type { TelemetryConsent }  from "./TelemetryConsent";
export type { TelemetryPreview }  from "./TelemetryPreview";
export type { TelemetryQueueStatus } from "./TelemetryQueueStatus";
export type { TelemetryStatus }   from "./TelemetryStatus";
// The wire shape itself — what a payload would contain, field for field.
export type { StagePayload }      from "./StagePayload";
export type { WireSettings }      from "./WireSettings";
export type { CounterReport }     from "./CounterReport";
export type { CrashReport }       from "./CrashReport";
export type { QualityReport }     from "./QualityReport";
export type { ProblemReport }     from "./ProblemReport";
export type { ReportContext }     from "./ReportContext";
// What the submit path did with a report the operator just wrote (E6).
export type { ReportOutcome }     from "./ReportOutcome";
export type { DisplayBucket }     from "./DisplayBucket";
export type { LibraryBucket }     from "./LibraryBucket";
export type { ThemeBucket }       from "./ThemeBucket";
export type { TelemetryArch }     from "./TelemetryArch";

/** Error shape returned by every Tauri command (see error.rs). */
export interface AppError {
  code:
    | "database"
    | "migration"
    | "not_found"
    | "conflict"
    | "validation"
    | "io"
    | "json"
    | "internal";
  message: string;
}
