// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How big the song library is.
 *
 * Coarse on purpose: library size is a decent proxy for how long a congregation
 * has used the app, so the bands are wide enough that no single church sits
 * alone in one.
 */
export type LibraryBucket = "under_50" | "50_200" | "200_1000" | "1000_5000" | "over_5000";
