// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveFrame } from "./LiveFrame";
import type { OutputState } from "./OutputState";

/**
 * A lightweight snapshot sent to the operator UI after each action.
 */
export type LiveSessionView = { service_id: string, index: number, total: number, output: OutputState, frame: LiveFrame, log_len: number, 
/**
 * When the session went live (unix ms) — drives the stage-display timer.
 */
started_at: bigint, };
