// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An operator action. The only way to mutate a session.
 */
export type LiveAction = { "type": "next" } | { "type": "previous" } | { "type": "go_to", index: number, } | { "type": "blackout" } | { "type": "show_logo" } | { "type": "show_message", text: string, } | { "type": "clear" };
