// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlideContent } from "./SlideContent";

/**
 * What should be on the main output right now. Derived from the cue + output
 * state; this is what the output process renders and the operator preview
 * mirrors.
 */
export type LiveFrame = { "kind": "slide", slide_content: SlideContent, } | { "kind": "black" } | { "kind": "logo" } | { "kind": "message", text: string, };
