// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A UI language the app offers (Phase 13.1 i18n).
 */
export type LocaleInfo = { code: string, name: string, };
