// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaAsset } from "./MediaAsset";

/**
 * A media asset plus whether its `original_path` currently exists on disk —
 * the browser shows a "broken, relink?" badge when `present` is false.
 */
export type MediaStatus = { asset: MediaAsset, present: boolean, };
