// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaAsset = { id: string, library_id: string, kind: string, original_path: string, content_hash: string, thumbnail_path: string | null, width: bigint | null, height: bigint | null, duration_ms: bigint | null, tags: string | null, imported_at: bigint, updated_at: bigint, };
