// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A connected monitor as reported by the OS. `index` is the position in the
 * enumeration and is the stable-enough key we assign roles against.
 */
export type MonitorInfo = { index: number, name: string, width: number, height: number, x: number, y: number, scale_factor: number, 
/**
 * The OS "primary" screen — assumed to be where the operator UI lives.
 */
is_primary: boolean, };
