// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the Settings card shows and toggles.
 *
 * Two booleans, not one, because they can honestly disagree: the operator can
 * have capture switched ON while the handler is NOT armed — the pending file
 * could not be opened, or the platform refused. Reporting only `enabled` would
 * tell an operator their rig is being watched when it is not.
 */
export type NativeCrashStatus = { 
/**
 * The persisted switch.
 */
enabled: boolean, 
/**
 * Whether a handler is actually installed in this process right now.
 */
armed: boolean, };
