// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HAlign } from "./HAlign";

/**
 * How the congregation output renders slides — independent of *which* screen
 * shows them (that's [`OutputConfig`]). Persisted per machine; the output
 * windows read it on open and update live when it changes.
 */
export type OutputAppearance = { 
/**
 * Multiplier on the base slide font size. 1.0 = default.
 */
text_scale: number, 
/**
 * Lyric/text colour (hex, e.g. "#ffffff").
 */
text_color: string, 
/**
 * Background colour (hex).
 */
bg_color: string, 
/**
 * Horizontal alignment of the lyric block.
 */
h_align: HAlign, 
/**
 * Show the section label ("Verse 1") on the congregation output. Many
 * churches want this off for the audience and on for the stage.
 */
show_section_label: boolean, 
/**
 * Render lyric lines in UPPERCASE.
 */
uppercase: boolean, 
/**
 * Line-height multiplier.
 */
line_height: number, };
