// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayAssignment } from "./DisplayAssignment";

/**
 * Persisted output configuration (the user's last-chosen role assignments).
 */
export type OutputConfig = { assignments: Array<DisplayAssignment>, };
