// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputResolution } from "./OutputResolution";
import type { OutputTransition } from "./OutputTransition";

/**
 * User-facing output display configuration persisted to
 * `output_display_config.json`. Covers the technical aspects of how the
 * output window is presented (resolution, safe-zone, transitions) separately
 * from the visual appearance (colours, fonts) which lives in
 * `OutputAppearance`.
 */
export type OutputDisplayConfig = { 
/**
 * Which monitor to use as the primary output (0-based index). Overridden
 * by the `OutputConfig` role assignments when those are set.
 */
primary_display_index: number, 
/**
 * The render resolution the output window targets.
 */
output_resolution: OutputResolution, 
/**
 * Percentage (5–20) of the screen to keep clear of text on each side.
 */
text_safe_zone_percent: number, 
/**
 * The transition applied when advancing from one cue to the next.
 */
transition: OutputTransition, 
/**
 * Duration of the transition in milliseconds (only used for non-cut transitions).
 */
transition_ms: number, };
