// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Target resolution for the output window.
 */
export type OutputResolution = "1920x1080" | "1280x720" | "3840x2160";
