// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The slide transition effect used when advancing cues on the output.
 */
export type OutputTransition = "cut" | "fade" | "slide_left" | "slide_right";
