// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the output is currently doing. `Normal` shows the cue at `index`;
 * `Blackout`/`Logo` override it without losing the cue position.
 */
export type OutputState = "normal" | "blackout" | "logo";
