// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the output is currently doing. `Normal` shows the cue at `index`;
 * `Blackout`/`Logo`/`Message` override it without losing the cue position
 * (the message text itself lives in [`LiveSession::message_text`] so this
 * stays `Copy`).
 */
export type OutputState = "normal" | "blackout" | "logo" | "message";
