// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A parsed-but-not-yet-resolved bible reference. The renderer shows
 * the canonical English book name when ambiguous so the user can verify.
 */
export type ParsedBibleRef = { 
/**
 * Canonical English book name (e.g. "John", "1 Corinthians").
 */
book: string, chapter: number, 
/**
 * `None` means "whole chapter".
 */
verse_start: number | null, 
/**
 * `None` means single verse (or whole chapter when verse_start is None).
 */
verse_end: number | null, };
