// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Person = { id: string, library_id: string, display_name: string, sort_name: string | null, external_ids: string | null, created_at: bigint, updated_at: bigint, };
