// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Service } from "./Service";

/**
 * Outcome of an import — what landed, and what needs a human's attention.
 */
export type PlanImportResult = { service: Service, 
/**
 * Songs matched to an existing library entry.
 */
matched_songs: number, 
/**
 * Titles of songs not found locally — created as empty stubs to fill in.
 */
created_songs: Array<string>, 
/**
 * Items that couldn't be imported faithfully (skipped, or placed as a
 * placeholder to finish manually).
 */
warnings: Array<string>, };
