// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One proposed item in a service plan.
 */
export type PlanItem = { 
/**
 * `song` | `scripture` | `note`.
 */
kind: string, 
/**
 * Human label for the item (song title, passage, or transition note).
 */
title: string, 
/**
 * Library song id — only set (and only kept) for `song` items that match
 * a real song in the library.
 */
song_id: string | null, 
/**
 * Suggested key for a song.
 */
key: string | null, 
/**
 * Scripture reference text (for `scripture` items).
 */
reference: string | null, 
/**
 * Free-text note / transition guidance.
 */
note: string | null, };
