// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportContext } from "./ReportContext";

/**
 * One manual "report a problem" submission.
 *
 * **E6 fills this; E5 always sent an empty list.** The field exists on the
 * wire from day one because `STAGE_OPTIONAL_PAYLOAD_KEYS` is empty by design
 * (the programme's Nøkkeldesign): the Worker requires every top-level key, so a
 * client that omitted `reports` until E6 would be rejected with a 400 — dropped
 * permanently, without retry, exactly the silent loss law 3 exists to prevent.
 */
export type ProblemReport = { at: number, context: ReportContext, 
/**
 * Free text, scrubbed and capped at [`super::MESSAGE_MAX_CHARS`].
 */
message: string, 
/**
 * The scrubbed log tail, capped at [`LOG_TAIL_MAX_CHARS`].
 */
logTail: string, };
