// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QualityReason } from "./QualityReason";
import type { QualityVerdict } from "./QualityVerdict";

/**
 * One finished live session's health.
 *
 * Numbers, booleans and closed enums only: no service name, no song title, no
 * display name, no path. What a support conversation needs from a Sunday is
 * whether the projector kept up, and these are the numbers that answer it.
 */
export type QualityRow = { 
/**
 * UUIDv7, per the repository convention.
 */
id: string, 
/**
 * A stable key for rows that can be produced twice (the startup
 * reconstruction sees the same leftover WAL on every launch until it is
 * resumed or cleared). `None` for ordinary rows. LOCAL ONLY — E5's payload
 * builder does not project it.
 */
dedupeKey: string | null, 
/**
 * Unix ms the session ended.
 */
at: number, durationSec: number, cueCount: number, outputChildRestarts: number, connectTimeouts: number, watchdogHolds: number, dispatchErrors: number, companionFailures: number, 
/**
 * The outputs ran as in-process windows rather than isolated processes.
 */
fallbackUsed: boolean, 
/**
 * A child left over from a crashed previous process was killed.
 */
staleChildReaped: boolean, abnormalEnd: boolean, recovered: boolean, 
/**
 * Interpolated 95th percentile of dispatch→ACK, or `None` when no cue was
 * ACKed (no isolated outputs were open, or the service had no cues).
 */
cueLatencyP95Ms: number | null, verdict: QualityVerdict, 
/**
 * Never empty: a clean session carries `[clean]`.
 */
reasons: Array<QualityReason>, };
