// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QualityReason } from "./QualityReason";
import type { QualityVerdict } from "./QualityVerdict";

/**
 * One finished live session's health, as it goes on the wire.
 *
 * [`QualityRow`] minus `id` and `dedupe_key`: both are local bookkeeping, and
 * the dedupe key in particular is derived from a session's start time and cue
 * count, which is more than the endpoint needs to know.
 */
export type QualityReport = { at: number, durationSec: number, cueCount: number, outputChildRestarts: number, connectTimeouts: number, watchdogHolds: number, dispatchErrors: number, companionFailures: number, fallbackUsed: boolean, staleChildReaped: boolean, abnormalEnd: boolean, recovered: boolean, cueLatencyP95Ms: number | null, verdict: QualityVerdict, reasons: Array<QualityReason>, };
