// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * WHY a session reached its verdict — a CLOSED set of codes, never prose.
 */
export type QualityReason = "output-restarted" | "hold-last-frame" | "abnormal-end" | "dispatch-errors" | "slow-cues" | "companion-failures" | "fallback-used" | "clean";
