// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happened to a report the operator just submitted.
 *
 * Every value is a true statement about bytes, not a reassurance. The dialog
 * says one of five things and never "sent" unless something was.
 */
export type ReportOutcome = "queued" | "sent" | "deferred-live" | "deferred-offline" | "no-endpoint";
