// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the operator was when they wrote a manual problem report. A CLOSED set
 * — the one field of a report that is not free text.
 */
export type ReportContext = "live" | "editor" | "settings" | "other";
