// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Service = { id: string, library_id: string, name: string, starts_at: bigint, notes: string | null, state: string, 
/**
 * Phase 11.2 — ISO-639-1 target for the live translation overlay. `None`
 * (the default) means no secondary line is shown. The cue compiler
 * pre-resolves every cue's translation into this language at "Go Live"
 * time, so the live output never makes a network call.
 */
secondary_language: string | null, created_at: bigint, updated_at: bigint, deleted_at: bigint | null, };
