// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reusable service template: an ordered list of cue-specs that can be
 * applied to any service to seed its queue in one click.
 */
export type ServiceTemplate = { id: string, name: string, description: string | null, 
/**
 * JSON-serialised `Vec<CueSpec>`.
 */
cue_specs: string, is_builtin: bigint, created_at: bigint, updated_at: bigint, };
