// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Service = { id: string, library_id: string, name: string, starts_at: bigint, notes: string | null, state: string, created_at: bigint, updated_at: bigint, deleted_at: bigint | null, };
