// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionCueCount } from "./SectionCueCount";

export type ServiceItemCues = { service_item_id: string, 
/**
 * Schema kind: "song" | "scripture" | "custom_deck" | "gap" | …
 */
kind: string, 
/**
 * Human title: song title, scripture reference, deck name, or the
 * humanized kind for placeholders.
 */
title: string, cue_count: number, 
/**
 * Slide count per section in play order (e.g. Verse 1 → 2, Chorus → 1).
 */
sections: Array<SectionCueCount>, };
