// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CueSpec } from "./CueSpec";

/**
 * Input for creating a user-defined service template.
 */
export type ServiceTemplateInput = { name: string, description: string | null, cue_specs: Array<CueSpec>, };
