// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The SundaySong catalog entry behind one *song* service item, keyed back to
 * the item it plays in. The live → SundaySong usage bridge (Phase 3 consumer)
 * needs the song id + title per service item; the planner already holds it, so
 * this is just the join surfaced. Non-song items carry no entry.
 */
export type ServiceItemSong = { 
/**
 * Canonical SundaySong catalog id.
 */
song_id: string, 
/**
 * Display title (for the `now_playing` bridge event).
 */
title: string, 
/**
 * Arrangement/translation variant shown, if the item names one.
 */
variant_id: string | null, };
