// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServiceItem = { id: string, service_id: string, position: bigint, kind: string, song_id: string | null, arrangement_id: string | null, key_override: string | null, bible_reference_id: string | null, custom_deck_id: string | null, media_asset_id: string | null, notes: string | null, created_at: bigint, updated_at: bigint, };
