// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanItem } from "./PlanItem";

/**
 * A proposed service the user can review and create.
 */
export type ServicePlan = { title: string, theme: string | null, items: Array<PlanItem>, warnings: Array<string>, };
