// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A content payload to be poured into a template's slots. Every field is
 * optional; a template only consumes the fields whose roles its slots declare.
 *
 * This is the *source* side of the apply-template flow: the gallery hands a
 * payload to [`map_content_to_slots`], which resolves it into the
 * `slot_name -> text` map that [`render_slide`] already understands.
 */
export type SlideContentPayload = { title: string | null, body: string | null, lyrics: string | null, reference: string | null, footer: string | null, image: string | null, };
