// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HAlign } from "./HAlign";

/**
 * The *resolved* look of one live cue, embedded on its [`SlideContent`] at
 * compile time (see `CueCompiler`). Derived from the cascade-resolved theme
 * tokens + template layout, so the output process needs no DB and no theme
 * lookup at show time. Every field is optional: `None` means "inherit the
 * operator's global `OutputAppearance`" — the cue only overrides what the
 * theme actually specifies.
 *
 * [`SlideContent`]: crate::services::cue_list::SlideContent
 */
export type SlideAppearance = { 
/**
 * CSS background — a colour or a gradient (themes use both).
 */
bg: string | null, 
/**
 * Lyric/text colour.
 */
text_color: string | null, 
/**
 * Theme font stack.
 */
font_family: string | null, 
/**
 * Horizontal alignment from the template's primary text slot.
 */
h_align: HAlign | null, 
/**
 * Multiplier applied ON TOP of the operator's `text_scale` (so a theme
 * with a bigger base size scales with — never fights — the operator's
 * "larger text" preference). Theme `body_size`/64 × slot `size_scale`.
 */
text_scale: number | null, };
