// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlideBackground } from "./SlideBackground";
import type { SlideBlock } from "./SlideBlock";

/**
 * The full editable design of one slide. Serialized into `slide.content`.
 */
export type SlideDoc = { background: SlideBackground, blocks: Array<SlideBlock>, };
