// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HAlign } from "./HAlign";
import type { SlideRect } from "./SlideRect";
import type { TextStyle } from "./TextStyle";
import type { VAlign } from "./VAlign";

/**
 * A single element on a slide. Internally tagged by `type` so the JSON looks
 * like `{ "type": "text", ... }` — the shape the cue compiler reads.
 *
 * `Image` is modelled now to leave room (per the Phase 3.1 plan) but has no
 * editor UI yet.
 */
export type SlideBlock = { "type": "text", id: string, text: string, rect: SlideRect, align: HAlign, valign: VAlign, style: TextStyle, } | { "type": "image", id: string, rect: SlideRect, 
/**
 * Media asset id or absolute path resolved at render time.
 */
src: string, };
