// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SlideContent = { 
/**
 * Optional section label shown on the stage display
 * (e.g. "Verse 1", "Chorus"). Musicians need this.
 */
section_label: string | null, 
/**
 * The actual text shown on the main output. Lines are pre-broken
 * for the current slide.
 */
text_lines: Array<string>, 
/**
 * Optional secondary line (translation) shown below the primary
 * line — Phase 11.2 fills this in.
 */
translation_lines: Array<string> | null, 
/**
 * Reference text shown small (e.g. "John 3:16").
 */
reference: string | null, };
