// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundKind } from "./BackgroundKind";

/**
 * Slide background. `value` is interpreted per `kind`: a CSS color for
 * `Color`, a CSS gradient for `Gradient`, an asset id/path for media.
 */
export type SlideBackground = { type: BackgroundKind, value: string, };
