// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a slot is for — drives which token colors/weights it inherits.
 */
export type SlotRole = "title" | "lyrics" | "reference" | "footer";
