// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a slot is for — drives which token colors/weights it inherits and how
 * the content payload is mapped into it (see [`map_content_to_slots`]).
 */
export type SlotRole = "title" | "body" | "lyrics" | "reference" | "footer" | "image";
