// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SongArrangement = { id: string, song_id: string, name: string, is_default: bigint, created_at: bigint, updated_at: bigint, };
