// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SongSection = { id: string, song_id: string, label: string, lyrics: string, chord_chart: string | null, display_order: bigint, created_at: bigint, updated_at: bigint, };
