// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SongInput = { library_id: string, title: string, language: string | null, default_key: string | null, tempo_bpm: bigint | null, ccli_song_id: string | null, tono_work_id: string | null, copyright_notice: string | null, };
