// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Song = { id: string, library_id: string, title: string, ccli_song_id: string | null, tono_work_id: string | null, copyright_notice: string | null, default_key: string | null, tempo_bpm: bigint | null, language: string, last_used_at: bigint | null, 
/**
 * Per-song theme override (cascade level 2). See `services::theme`.
 */
theme_id: string | null, 
/**
 * Per-song template override (cascade level 2).
 */
template_id: string | null, created_at: bigint, updated_at: bigint, deleted_at: bigint | null, };
