// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A7 — one row of the song-usage log: a song that provably held the
 * congregation output during one service, with the licensing metadata snapshot
 * TONO/CCLI reporting needs.
 *
 * The metadata is COPIED in rather than joined at read time, so a song deleted
 * from the library in February doesn't erase the January report. See
 * `sql/0010_song_usage.sql`.
 */
export type SongUsageRow = { id: string, service_id: string, service_name: string, 
/**
 * Local civil date, `YYYY-MM-DD` — the date the report shows.
 */
service_date: string, song_id: string, title: string, author: string | null, ccli_song_id: string | null, tono_work_id: string | null, copyright_notice: string | null, first_shown_at: bigint, last_shown_at: bigint, 
/**
 * Total time the song actually held the output, in ms.
 */
visible_ms: bigint, 
/**
 * Separate times it was on screen in this service (a reprise = 2).
 */
show_count: bigint, created_at: bigint, updated_at: bigint, };
