// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which panels a stage display shows. Presets are just named configs.
 */
export type StageDisplayConfig = { id: string, name: string, 
/**
 * Large preview of what's on the main output now.
 */
show_current_slide: boolean, 
/**
 * Smaller preview of the next cue.
 */
show_next_slide: boolean, 
/**
 * Render lyrics as big plain text instead of a slide preview.
 */
lyrics_large: boolean, 
/**
 * "Verse 1" / "Chorus" — musicians need this.
 */
show_section_label: boolean, 
/**
 * Wall clock.
 */
show_clock: boolean, 
/**
 * Count-up since the service went live.
 */
show_service_timer: boolean, 
/**
 * Notes / sermon outline / chord chart.
 */
show_notes: boolean, };
