// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CounterReport } from "./CounterReport";
import type { CrashReport } from "./CrashReport";
import type { ProblemReport } from "./ProblemReport";
import type { QualityReport } from "./QualityReport";
import type { TelemetryArch } from "./TelemetryArch";
import type { TelemetryOs } from "./TelemetryOs";
import type { WireSettings } from "./WireSettings";

/**
 * The complete payload — the only thing that ever leaves the machine.
 */
export type StagePayload = { 
/**
 * [`PAYLOAD_SCHEMA`] at build time.
 */
schema: number, 
/**
 * The consent scope this payload was collected under, so the endpoint can
 * prove per row which question the operator actually answered.
 */
consentVersion: number, 
/**
 * The random, machine-local install id. Never derived from anything.
 */
installId: string, 
/**
 * Unix ms (UTC) **the payload was built**.
 *
 * Divergence note: the E5 brief glossed this as a compile-time build stamp.
 * It is not, and must not be: the programme pins the envelope as "som Rec",
 * where `builtAt` is the payload's own build time, and a constant baked in
 * at compile time would give every payload from one release an identical
 * timestamp — useless for ordering and indistinguishable from a stuck
 * clock. The app's build identity is already carried, precisely, by
 * [`Self::app_version`].
 */
builtAt: number, 
/**
 * `CARGO_PKG_VERSION` of the running build.
 */
appVersion: string, os: TelemetryOs, arch: TelemetryArch, 
/**
 * UI language, PRIMARY SUBTAG ONLY (`nb-NO` → `nb`). `None` when the app
 * has not recorded a choice. The region subtag is deliberately discarded:
 * language answers a real product question (which translations get used),
 * region narrows an anonymous install towards a place.
 */
language: string | null, settings: WireSettings, counters: Array<CounterReport>, crashes: Array<CrashReport>, quality: Array<QualityReport>, 
/**
 * Always empty until E6 — see [`ProblemReport`] for why the key is here
 * anyway.
 */
reports: Array<ProblemReport>, };
