// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The top-bar sync indicator state.
 */
export type SyncStatus = "local_only" | "synced" | "syncing" | "offline" | "conflict" | "paused_live";
