// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A compact status line for the settings panel: how many are waiting, how old
 * the oldest is, and what went wrong last.
 */
export type TelemetryQueueStatus = { 
/**
 * Rows not yet delivered (pending + sending).
 */
pending: number, 
/**
 * Rows that ran out of attempts.
 */
failed: number, 
/**
 * Unix ms (UTC) the oldest undelivered payload was built.
 */
oldestAt: number | null, 
/**
 * The most recent failure message, if any.
 */
lastError: string | null, };
