// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What "show me what you send" hands the UI: the real payload as pretty JSON,
 * plus the two facts needed to label it honestly.
 */
export type TelemetryPreview = { 
/**
 * The payload, pretty-printed. Byte-identical in CONTENT to what would be
 * queued — see `preview_matches_the_queued_bytes` in the tests.
 */
json: string, 
/**
 * True when this is literally the next payload (consent is active, so the
 * watermarks are real). False when consent is off: there is no "next", so
 * the preview shows the whole local history instead — the honest answer to
 * "what WOULD you send", and a better one than an empty shell.
 */
isNextPayload: boolean, 
/**
 * Whether the payload carries anything at all.
 */
isEmpty: boolean, };
