// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a flush did, for the renderer.
 */
export type TelemetryFlush = { rowsWritten: number, countersWritten: number, 
/**
 * A service was live (or a live command was mid-flight): nothing was
 * written, and nothing was lost.
 */
skippedLive: boolean, };
