// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The operating system, as a CLOSED set. `std::env::consts::OS` is a `&str`
 * with no compile-time guarantee about its contents, so it is mapped here
 * rather than forwarded.
 */
export type TelemetryOs = "macos" | "windows" | "linux" | "other";
