// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a queued payload is in its lifecycle. Serialised lowercase, matching
 * the `status` CHECK constraint in migration 0008.
 */
export type TelemetryStatus = "pending" | "sending" | "failed";
