// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Template = { id: string, library_id: string | null, name: string, slots: string, is_builtin: bigint, created_at: bigint, updated_at: bigint, };
