// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The output role a service template targets — *who* watches the stage
 * display when the template runs. Templates carry this so the operator can see,
 * per template, which panel layout the screen will surface. The frontend
 * persists the per-template assignment (per device); this enum + mapping is the
 * shared source of truth for the panel layout each role gets, mirrored in
 * `src/features/services/templateRoles.ts`.
 */
export type TemplateRole = "worship-leader" | "musician" | "operator" | "congregation";
