// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateSlot } from "./TemplateSlot";

/**
 * The layout stored in `template.slots` (JSON).
 */
export type TemplateLayout = { slots: Array<TemplateSlot>, };
