// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HAlign } from "./HAlign";
import type { SlideRect } from "./SlideRect";
import type { SlotRole } from "./SlotRole";
import type { VAlign } from "./VAlign";

/**
 * One named region in a template. Themes style it; content fills it.
 */
export type TemplateSlot = { 
/**
 * Stable key used to address the slot when filling content.
 */
name: string, role: SlotRole, rect: SlideRect, align: HAlign, valign: VAlign, 
/**
 * Multiplier on the theme's `body_size` (e.g. title 1.4, reference 0.45).
 */
size_scale: number, };
