// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typographic styling for a text block. `size` is px @1080 (see module docs).
 */
export type TextStyle = { 
/**
 * Font family; `None` falls back to the theme/default stage font.
 */
family: string | null, size: number, weight: number, color: string, italic: boolean, 
/**
 * CSS shadow string, e.g. `"0 2px 8px rgba(0,0,0,0.6)"`. `None` = none.
 */
shadow: string | null, };
