// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many themes the operator made themselves. Same half-open convention, on a
 * range where the interesting question is "does anyone customise at all".
 */
export type ThemeBucket = "under_5" | "5_20" | "20_50" | "over_50";
