// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlideBackground } from "./SlideBackground";

/**
 * Color + typography tokens stored in `theme.tokens` (JSON).
 */
export type ThemeTokens = { background: SlideBackground, text_color: string, accent_color: string, font_family: string, heading_weight: number, 
/**
 * Base body text size in px on the virtual 1080 stage; slots scale it.
 */
body_size: number, shadow: string | null, };
