// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An entry in the TONO streaming report.
 */
export type TonoEntry = { song_id: string, title: string, };
