// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of translating a block of lines.
 */
export type TranslationResult = { target_language: string, 
/**
 * One translated line per source line, in order.
 */
lines: Array<string>, warnings: Array<string>, };
