// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single cross-type search hit. `kind` is "song" | "bible" | "service".
 */
export type UniversalHit = { kind: string, id: string, title: string, subtitle: string, };
