// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which update ring this install follows.
 *
 * Defaults to [`UpdateChannel::Stable`] — an unreadable, missing or malformed
 * settings file resolves to stable, never to beta (an operator must opt in
 * deliberately; a corrupted file must not silently move a church onto betas).
 */
export type UpdateChannel = "stable" | "beta";
