// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateChannel } from "./UpdateChannel";

/**
 * What the operator is offered when a newer signed build exists on the ring.
 */
export type UpdateInfo = { 
/**
 * Version available on the ring.
 */
version: string, 
/**
 * Version currently running.
 */
current_version: string, 
/**
 * Ring this manifest came from.
 */
channel: UpdateChannel, 
/**
 * Release notes from the manifest, if any.
 */
notes: string | null, };
