// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayBucket } from "./DisplayBucket";
import type { LibraryBucket } from "./LibraryBucket";
import type { ThemeBucket } from "./ThemeBucket";
import type { UpdateChannel } from "./UpdateChannel";

/**
 * The technical settings block: ten closed enum/bool/band fields, and nothing
 * that could carry a name.
 *
 * Every field is gathered from real app state by [`WireSettings::gather`] —
 * see that function for exactly which file or table each one reads, because
 * "honest" is a property of the reads, not of the field names.
 */
export type WireSettings = { 
/**
 * Displays actually driven by SundayStage (role != off).
 */
outputCount: number, 
/**
 * How many displays are connected, as a band.
 */
displayCountBucket: DisplayBucket, 
/**
 * A display is assigned the stage-facing role.
 */
stageDisplayEnabled: boolean, 
/**
 * The companion phone transport is configured.
 */
companionEnabled: boolean, 
/**
 * The outputs run as in-process windows rather than isolated processes —
 * i.e. the crash-isolation fallback is in effect.
 */
fallbackInProcess: boolean, librarySongsBucket: LibraryBucket, themeCountBucket: ThemeBucket, 
/**
 * An Anthropic key is configured. NEVER the key, and never a prefix of it.
 */
aiConfigured: boolean, 
/**
 * Cloud sync is configured.
 */
syncEnabled: boolean, 
/**
 * Which update ring this install follows.
 */
updateRing: UpdateChannel, };
